### ISSUE TITLE
FPS Limit?

### ISSUE THREAD

**Issue by fernpi** [Jackojc/olcNotSoConsoleGameEngine#2]
how to pass fps limit?

https://im5.ezgif.com/tmp/ezgif-5-18e9d8cc4ecb.gif

**Comment by Jackojc** [comment]
It just runs as fast as possible right now, you can implement a manual fps limit inside your derived class.

**Comment by fernpi** [comment]
olcConsoleGameEngineSDL passes the FPS limit while olcNotSoConsoleGameEngine only goes 70

https://imgur.com/a/n32oQnt

**Comment by Jackojc** [comment]
Yeah, this version is very slow
